DROP TABLE IF EXISTS guitars;

CREATE TABLE IF NOT EXISTS guitars (
  id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY
  , user_id VARCHAR(50) NOT NULL
  , brand VARCHAR(50) NOT NULL
  , model VARCHAR(50) NOT NULL
  , year SMALLINT NULL
  , color VARCHAR(50) NULL
)
